//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eproj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int id { get; set; }
        public string cont_name { get; set; }
        public string email { get; set; }
        public string cont_address { get; set; }
        public string msg { get; set; }
        public string city { get; set; }
        public string country { get; set; }
    }
}
