//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eproj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.carts = new HashSet<cart>();
            this.order_detail = new HashSet<order_detail>();
        }
    
        public int cust_id { get; set; }
        
        [StringLength(100, MinimumLength = 3)]
        [RegularExpression("[A-Z][a-z]")]

        [Display(Name="Username")]

        public string fname { get; set; }

      
        
        
        public string lname { get; set; }
        public Nullable<long> contact { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string cust_address { get; set; }
       
        
        public string cust_username { get; set; }
        public string cust_pass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_detail> order_detail { get; set; }
    }
}
