//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eproj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.employee_img = new HashSet<employee_img>();
        }
    
        public int emp_id { get; set; }
        public string emp_username { get; set; }
        public string emp_pass { get; set; }
        public string emp_email { get; set; }
        public string eimg { get; set; }
        public string country { get; set; }
        public Nullable<long> phone { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_img> employee_img { get; set; }
    }
}
